modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/instant-tnt/issues"
license="GPLv3+"
[[mods]]
    modId="instant_tnt"
    version="${file.jarVersion}"
    displayName="Instant TNT Mod"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/instant-tnt"
    # (in the root of the mod JAR)
    #logoFile="instant_tnt.png" #optional
    authors="justAm0dd3r" #optional
    description='''This mod makes tnt automatically explode when placed.'''

[[dependencies.instant_tnt]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.instant_tnt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    ordering="NONE"
    side="BOTH"
